### ISSUE TITLE
Moving file on import not working

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#1209]
## VERSION INFORMATION

Server Version: v5.0.0.43, Channel: Dev, Tag: v5.0.0-dev.43, Commit: d66b2821142a75d4afd586b0a4e496c26aa20a40

## LOG FILE

[2024-12-12.log](https://github.com/user-attachments/files/18107096/2024-12-12.log)

## DESCRIPTION

Get the follow errors when trying to process files from the drop folder

`Warn|Shoko.Server.Renamer.RenameFileService > An error occurred while trying to find a destination for E:\AnimeDrop\[SubsPlease] Amagami-san Chi no Enmusubi - 03 (1080p) [8606E7CF].mkv: The renamer "WebAOMRenamer" could not find a valid destination.`

## STEPS TO REPRODUCE

1. Setup an Import Folder with type = `Drop`
2. Setup an Import Folder with type = `Destination`
3. Scan the Drop Import Folder
4. Verify the error/warning in log
5. Verify that the file has been added to the collection successfully (can see in episode of collection tab)
6. Verify that the folder has NOT been moved to the destination

NOTE - This is a fresh install, and by default the renamer script was empty
I created a new rename script with default WebAOM settings and set it as default

**Comment by revam** [comment]
@harshithmohan didn't you fix this in a daily? idr which version.

**Comment by harshithmohan** [comment]
> @harshithmohan didn't you fix this in a daily? idr which version.

I did. In 5.0.0.65

**Comment by revam** [comment]
so @jmediamanager it should be fixed in a newer daily, and in the next stable, so closing this now. also hello. 👋

**Comment by harshithmohan** [comment]
Just to add, it won't automatically fix it for everyone when they update. It's fixed for new users

**Comment by jmediamanager** [comment]
@revam hello :)
@harshithmohan if only fixed for new users, does it mean I have to start from scratch?

**Comment by revam** [comment]
didn't you already fix it by creating a new renamer config and setting said config as the default config to use? @jmediamanager

**Comment by jmediamanager** [comment]
> didn't you already fix it by creating a new renamer config and setting said config as the default config to use? @jmediamanager

Yup, updated to 5.0.0.86
Created a new renamer after the update and still having the same issue. Attaching log if relevant
[2024-12-13.log](https://github.com/user-attachments/files/18118543/2024-12-13.log)

**Comment by jmediamanager** [comment]
@revam @harshithmohan FYI - I traced through the code myself, and found that it was failing on the disk space checks
So I set the setting for `SkipDiskSpaceChecks` to true, and now the moving works fine
Although it renames the file now, even though I have "Rename on import" disabled, but I can live with that

**Comment by harshithmohan** [comment]
I thought we were talking about the script being empty. *That* was fixed 😅

**Comment by jmediamanager** [comment]
Oh well yes I guess the script was fixed then :)

**Comment by revam** [comment]
> @revam @harshithmohan FYI - I traced through the code myself, and found that it was failing on the disk space checks So I set the setting for `SkipDiskSpaceChecks` to true, and now the moving works fine Although it renames the file now, even though I have "Rename on import" disabled, but I can live with that

Was it during an automatic rename/move job or in the renamer utility in the Web UI that it potentially wasn't respecting the "Rename on Import" setting?

**Comment by jmediamanager** [comment]
During the import process (i.e. press "rescan folder" from the Web UI)

**Comment by harshithmohan** [comment]
@ElementalCrisis More information required from whom? 🤔

**Comment by ElementalCrisis** [comment]
I added that since it seems it was still being investigated. 

Issue closed now so no longer needed.

**Comment by harshithmohan** [comment]
Damn it, I forgot to remove the label

**Comment by Tech3-PhilipNickels** [comment]
Incase helpful mentioning the SkipDiskSpaceChecks to true just fixed this for me today. 

This is with my destination set as a network share and the share is ~400TB with about ~126TB free incase maybe its a size thing.  

Was getting errors like this:

[2026-07-21 06:27:58:316] Info|RenameMoveFileJob_VideoLocalID:80516 > Processing RenameMoveFileJob: ANIME_TO_SORT\[ASW] Oni no Hanayome - 01 [1080p HEVC][3B97D6E5].mkv
[2026-07-21 06:27:58:316] Warn|Shoko.Server.Renamer.RenameFileService > An error occurred while trying to find a destination for \\172.16.6.24\nas\Insync\The_Media_Library_All\The_Media_Library_To_Sort\ANIME_TO_SORT\[ASW] Oni no Hanayome - 01 [1080p HEVC][3B97D6E5].mkv: The renamer "WebAOMRenamer" could not find a valid destination.
[2026-07-21 06:27:58:419] Info|RenameMoveFileJob_VideoLocalID:80587 > Processing RenameMoveFileJob: ANIME_TO_SORT\[ASW] Oni no Hanayome - 02 [1080p HEVC][E24C66BA].mkv
[2026-07-21 06:27:58:419] Warn|Shoko.Server.Renamer.RenameFileService > An error occurred while trying to find a destination for \\172.16.6.24\nas\Insync\The_Media_Library_All\The_Media_Library_To_Sort\ANIME_TO_SORT\[ASW] Oni no Hanayome - 02 [1080p HEVC][E24C66BA].mkv: The renamer "WebAOMRenamer" could not find a valid destination.


After updating the value and restarting the server process/service I'm now getting what appears to be success's" 
[2026-07-21 09:25:42:379] Info|RenameMoveFileJob_VideoLocalID:76292 > Processing RenameMoveFileJob: Onmyou Kaiten Re։Verse\[ASW]_Onmyo_Kaiten_Re-Birth_Verse_-_06_(1920x1080_HEVC_10bit)_[771A0161].mkv
[2026-07-21 09:25:42:442] Info|ProcessFileJob_VideoLocalID:76348 > Processing ProcessFileJob: Onmyou Kaiten Re։Verse\[ASW]_Onmyo_Kaiten_Re-Birth_Verse_-_07_(1920x1080_HEVC_10bit)_[5EF067E9].mkv
[2026-07-21 09:25:42:442] Info|ProcessFileJob_VideoLocalID:76348 > Queuing GET for AniDB_Anime: 19200

and 

[2026-07-21 09:12:25:990] Info|Shoko.Server.Services.VideoLocal_PlaceService > Moving file from \\172.16.6.24\nas\Insync\The_Media_Library_All\The_Media_Library_To_Sort\**ANIME_TO_SORT**\[ASW] Futsutsuka na Akujo dewa Gozaimasu ga - 02 [1080p HEVC][4A318F73].mkv to \\172.16.6.24\nas\Insync\The_Media_Library_All\**Anime_AniDB_Shoko**\Futsutsuka na Akujo de wa Gozaimasu ga։ Suuguu Chouso Torikae Den\[ASW]_Though_I_Am_an_Inept_Villainess-_Tale_of_the_Butterfly-Rat_Body_Swap_in_the_Maiden_Court_-_02_(1920x1080_HEVC_10bit)_[4A318F73].mkv

Looks like there is still some type of underlying issue. I'm running: 
Server Version: 5.3.1.0 (76af481)
Server Chanel: Stable
Web UI Version: 2.5.4 (2.5.4)
Web UI Channel: Stable

My import settings are:
Import On Start: Yes
Rename on Import: Yes
Move on Import: Yes
Allow relocation inside destination on import: Yes
Delete duplicates on import: No
Set file as watched if episode is watched: Yes
Video Extensions: MKV,AVI,MP4,MOV,OGM,WMV,MPG,MPEG,MK3D,M4V

Now to process a multi month backlog..... Happy to provide logs all the way back to 2019 and run other tests if helpful.
